### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by testujemai** [davidmartinrius/speech-dataset-generator#15]
Trying to run it on Kaggle. When pyannote starts, it writes this error.

self.iterate_datasets(datasets, transcription, output_directory, path_to_audio_file, existing_speakers)
  File "/kaggle/working/speech-dataset-generator/speech_dataset_generator/dataset_generator/dataset_generator.py", line 458, in iterate_datasets
    for dataset in datasets:
TypeError: 'NoneType' object is not iterable

Any ideas please?

**Comment by davidmartinrius** [comment]
Hi @testujemai , how are you doing?

I don't have enough information to analyze it.

What command and what parameters are you using to run it?

Probably you did not use the parameter --datasets [dataset_name] but I am not sure of this.

**Comment by testujemai** [comment]
Thanks for fast reply @davidmartinrius.

I'm doing step by step your example notebook. The command I used: 
`!python speech_dataset_generator/main.py --youtube_download https://www.youtube.com/watch?v=ExJZAegsOis --output_directory ./outputs/output_youtube --range_times 5-15 --enhancers deepfilternet resembleai`
But it is the same error on every other command. I though I don't need to use --datasets parameter if I want ljspeech by default.

Btw, very nice project!

**Comment by davidmartinrius** [comment]
Great, thanks!
