### ISSUE TITLE
deepspeed Error (Windows)

### ISSUE THREAD

**Issue by MethanJess** [davidmartinrius/speech-dataset-generator#8]
ERROR: Could not find a version that satisfies the requirement deepspeed==0.12.4 (from resemble-enhance) (from versions: 0.3.1.dev1, 0.3.1.dev2, 0.3.1.dev3, 0.3.1.dev4, 0.3.1.dev5, 0.3.1.dev6, 0.3.1.dev7, 0.3.1.dev8, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.3.7, 0.3.8, 0.3.9, 0.3.10, 0.3.11, 0.3.12, 0.3.13, 0.3.14, 0.3.15, 0.3.16, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.4.5, 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.5.5, 0.5.6, 0.5.7, 0.5.8, 0.5.9, 0.5.10, 0.6.0, 0.6.1, 0.6.3, 0.6.4, 0.6.5, 0.6.6, 0.6.7, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.7.4, 0.7.5, 0.7.6, 0.7.7, 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.9.5, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.11.0, 0.11.1, 0.11.2, 0.12.0, 0.12.1, 0.12.2, 0.12.3, 0.12.4, 0.12.5, 0.12.6, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.13.4, 0.13.5, 0.14.0)
ERROR: No matching distribution found for deepspeed==0.12.4

(This error appears when attempting to do "pip install -r requirements.txt".
This is very odd, because the 0.12.4 version is already listed in the available versions)

**Comment by MethanJess** [comment]
As a note, on Windows, the commands to make an environment is slightly different, not sure if this affects anything
`python3.10 -m venv venv` on Windows is: `python -m venv venv ` (I already have Python3.10.0 installed on my system)
`source venv/bin/activate` on Windows is: `.\venv\Scripts\activate`

**Comment by davidmartinrius** [comment]
The commands to activate the environment on Windows are ok.

Please, verify which version returns ```python --version```
using command 'python' is not the same as 'python3.10'. Even if you have installed python3.10 your system can be using another version if you did not update the python version reference.

On the other hand and supposing the python version is the correct one:
execute this: ```pip install --upgrade pip```

Then execute the pip install -r requirements.txt again.

If it fails again  try to add deepspeed (with no version) in the requirements.txt

**Comment by MethanJess** [comment]
The output of `python --version` is Python 3.10.0

My pip was outdated, updating it was a little complex but I did upgrade it by manually downloading the "get-pip.py" file.
After updating, I started getting torch errors that I fixed by manually doing `pip install torch`
Also had to do a pip install numpy

But after that, I got another error

 ```
error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      test.c
      LINK : fatal error LNK1181: cannot open input file 'aio.lib'
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Sietrx\AppData\Local\Temp\pip-install-93mmgo4j\deepspeed_77ab570f234b47fc843069c6102b6a04\setup.py", line 183, in <module>
          abort(f"Unable to pre-compile {op_name}")
        File "C:\Users\Sietrx\AppData\Local\Temp\pip-install-93mmgo4j\deepspeed_77ab570f234b47fc843069c6102b6a04\setup.py", line 52, in abort
          assert False, msg
      AssertionError: Unable to pre-compile async_io
      [WARNING] Torch did not find cuda available, if cross-compiling or running with cpu only you can ignore this message. Adding compute capability for Pascal, Volta, and Turing (compute capabilities 6.0, 6.1, 6.2)
      DS_BUILD_OPS=1
       [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
       [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
       [WARNING]  One can disable async_io with DS_BUILD_AIO=0
       [ERROR]  Unable to pre-compile async_io
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.
```

I did the `set DS_BUILD_AIO=0` command, but to no avail.
This is probably because of libaio, which is a Linux exclusive package from what I've heard....

At this point, do you have a simple WhisperX large-3 script that just splits an audio file and transcribes it into the metavoice dataset format? (sample_dataset.csv, and sample_val_dataset.csv)
if so, please provide it, thank you.

**Comment by davidmartinrius** [comment]
I think using get-pip.py is to install pip. You already had installed pip.

Please, create a new environment, upgrade pip and then install the requirements, in this order.

The way to upgrade pip is

python -m pip install --upgrade pip

**Comment by MethanJess** [comment]
Just made a a new environment and did `python -m pip install --upgrade pip`
And, I am getting an issue to do with pytorch


```
error: subprocess-exited-with-error
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      [WARNING] Unable to import torch, pre-compiling ops will be disabled. Please visit https://pytorch.org/ to see how to properly install torch on your system.
       [WARNING]  unable to import torch, please install it if you want to pre-compile any deepspeed ops.
      DS_BUILD_OPS=1
      Traceback (most recent call last):
        File "D:\D_Apps\SD-V2\speech-dataset-generator\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "D:\D_Apps\SD-V2\speech-dataset-generator\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "D:\D_Apps\SD-V2\speech-dataset-generator\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\Sietrx\AppData\Local\Temp\pip-build-env-ywqdwwo3\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\Sietrx\AppData\Local\Temp\pip-build-env-ywqdwwo3\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\Sietrx\AppData\Local\Temp\pip-build-env-ywqdwwo3\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\Sietrx\AppData\Local\Temp\pip-build-env-ywqdwwo3\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 147, in <module>
      AssertionError: Unable to pre-compile ops without torch installed. Please install torch before attempting to pre-compile ops.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
```

I tried installing pytorch with this command
`pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
`
But, I still got the same error...

**Comment by davidmartinrius** [comment]
Well keep in mind that as you reported https://github.com/davidmartinrius/speech-dataset-generator/issues/7#issuecomment-2030062736 you have cuda 11.5 installed. You tried to install torch with cuda 12.1

**Comment by MethanJess** [comment]
Yeah right, my cuda was 12.2, and pytorch only allows 12.1, so I downgraded cuda to 12.1 and made a new environment, yet i still get the same error

**Comment by MethanJess** [comment]
Thanks! I'd really appreciate :)

**Comment by davidmartinrius** [comment]
Hi I have this in mind. I will check it this weekend.

**Comment by davidmartinrius** [comment]
> Just made a a new environment and did `python -m pip install --upgrade pip` And, I am getting an issue to do with pytorch
> 
> ```
> error: subprocess-exited-with-error
>   × Getting requirements to build wheel did not run successfully.
>   │ exit code: 1
>   ╰─> [20 lines of output]
>       [WARNING] Unable to import torch, pre-compiling ops will be disabled. Please visit https://pytorch.org/ to see how to properly install torch on your system.
>        [WARNING]  unable to import torch, please install it if you want to pre-compile any deepspeed ops.
>       DS_BUILD_OPS=1
>       Traceback (most recent call last):
>         File "D:\D_Apps\SD-V2\speech-dataset-generator\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
>           main()
>         File "D:\D_Apps\SD-V2\speech-dataset-generator\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
>           json_out['return_val'] = hook(**hook_input['kwargs'])
>         File "D:\D_Apps\SD-V2\speech-dataset-generator\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
>           return hook(config_settings)
>         File "C:\Users\Sietrx\AppData\Local\Temp\pip-build-env-ywqdwwo3\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
>           return self._get_build_requires(config_settings, requirements=['wheel'])
>         File "C:\Users\Sietrx\AppData\Local\Temp\pip-build-env-ywqdwwo3\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
>           self.run_setup()
>         File "C:\Users\Sietrx\AppData\Local\Temp\pip-build-env-ywqdwwo3\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
>           super().run_setup(setup_script=setup_script)
>         File "C:\Users\Sietrx\AppData\Local\Temp\pip-build-env-ywqdwwo3\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
>           exec(code, locals())
>         File "<string>", line 147, in <module>
>       AssertionError: Unable to pre-compile ops without torch installed. Please install torch before attempting to pre-compile ops.
>       [end of output]
> 
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: subprocess-exited-with-error
> 
> × Getting requirements to build wheel did not run successfully.
> │ exit code: 1
> ╰─> See above for output.
> ```
> 
> I installed pytorch with this command `pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121 ` But, I still got the same error...

I have good and bad news. The good new is that I got the same error as you. The bad is that I still did not solve it. But I am looking for a way to fix it.

**Comment by MethanJess** [comment]
Interesting... my only idea is that maybe there are Linux exclusive packages, if i remember correctly, this project uses `libaio` which is a Unix exclusive package that doesn't work on Windows, but i could be wrong. Good luck!

**Comment by davidmartinrius** [comment]
I am going to close this issue, as I have not enough time to investigate how to run it on Windows. By now it is only compatible in Linux.

If anyone know how to solve this, please feel free to reopen this issue.

Thanks!
